# This is a basic workflow that is manually triggered

name: automatic unit test

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v1
      with:
        python-version: '3.8'  # Specify the Python version you are using
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flask flask-testing
    - name: Run tests
      run: |
        python -m unittest discover -s diyml/Backend/Tests
